service: lambda-import-s3-to-dynamodb

provider:
  name: aws
  lambdaHashingVersion: 20201221
  runtime: nodejs12.x
  deploymentBucket: belmino.lambda.code.dbz
  region: us-east-1
  environment:
    S3_DBZ_INPUT_BUCKET: belmino.dbz.json.input
    S3_DBZ_PROCESSED_BUCKET: belmino.dbz.json.processed

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
          Resource:
            - 'arn:aws:s3:::${self:provider.environment.S3_DBZ_INPUT_BUCKET}/*'
            - 'arn:aws:s3:::${self:provider.environment.S3_DBZ_PROCESSED_BUCKET}/*'

functions:
  import:
    handler: importHandler.importDBZJsonToDynamodDB
    events:
      - s3:
          bucket: ${self:provider.environment.S3_DBZ_INPUT_BUCKET}
          event: s3:ObjectCreated:*

#resources:
#  Resources:
#    S3InputBucket:
#      Type: 'AWS::S3::Bucket'
#     Properties:
#      BucketName: ${self:provider.environment.S3_DBZ_INPUT_BUCKET}
#    S3ProcessedBucket:
#      Type: 'AWS::S3::Bucket'
#      Properties:
#        BucketName: ${self:provider.environment.S3_DBZ_PROCESSED_BUCKET}